### ISSUE TITLE
CSS文本左右边缘对齐

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#134]
### 效果
![image](https://user-images.githubusercontent.com/10903843/64085444-58664880-cd65-11e9-9020-d814c010c790.png)

### 代码
```css
.label {
  width: 100px;
  padding: 0 10px;
  text-align-last: justify;
}
```

```html
<div class="label">测试</div>
<div class="label">测试一</div>
<div class="label">测试测试</div>
```
