### ISSUE TITLE
uniapp表格

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#139]
> uniapp不能直接使用`table`标签, 所以只有使用`view`标签加上`flex`布局了

### 示例
![image](https://user-images.githubusercontent.com/10903843/64580279-4f562680-d3b8-11e9-937a-0793a4e41663.png)

### 代码
```html
<view class="table">
  <view class="thead">
    <view class="tr">
      <view class="th">test1</view>
      <view class="th">test2</view>
      <view class="th">test3</view>
    </view>
  </view>
  <view class="tbody">
    <view class="tr">
      <view class="td">t1</view>
      <view class="td">t2</view>
      <view class="td">t3</view>
    </view>
    <view class="tr">
      <view class="td">t1</view>
      <view class="td">t2</view>
      <view class="td">t3</view>
    </view>
    <view class="tr">
      <view class="td">t1</view>
      <view class="td">t2</view>
      <view class="td">t3</view>
    </view>
    <view class="tr">
      <view class="td">t1</view>
      <view class="td">t2</view>
      <view class="td">t3</view>
    </view>
  </view>
</view>
```
```css
.table {
    width: 100%;
    display: flex;
    flex-direction: column;
    .empty {
      padding: 20upx 0;
      font-size: 24upx;
      color: #333;
      text-align: center;
    }
    .tr {
      display: flex;
      align-items: center;
      border-bottom: 2upx solid #ddd;
      .th {
        flex: 1;
        padding: 10upx 0;
        color: #333;
        text-align: center;
        background: #fff;
      }
      .td {
        flex: 1;
        padding: 10upx 0;
        font-size: 24upx;
        color: #999;
        text-align: center;
      }
    }
  }
```
