### ISSUE TITLE
CSS媒体查询, 系统颜色主题

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#193]
### 代码
```css
@media (prefers-color-scheme: light) {
  .themed {
    background: white;
    color: black;
  }
}

@media (prefers-color-scheme: dark) {
  .themed {
    background: black;
    color: white;
  }
}
```

### 参考资料
https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme
