### ISSUE TITLE
input type="number" 不显示后面的上下按钮

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#21]
### CSS里将样式除去
```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
input[type="number"]{
  -moz-appearance: textfield;
}
```
