### ISSUE TITLE
vue中css使用webpack别名来获取文件

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#238]
使用 `~@`即可

例如
```css
.top-bg {
  height: 1600px;
  background: url(~@/assets/package-bg.png) center no-repeat;
}
```
