### ISSUE TITLE
css网页黑暗模式

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#288]
```css
html[theme='dark-mode'] {
  filter: invert(1) hue-rotate(180deg);
}
```
