### ISSUE TITLE
flex布局子元素设置flex:1, 导致高度(宽度)超过父元素的高度(宽度)

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#479]
### 方法
可以给子元素设置高度为0(宽度为0)
```css
.child {
  flex: 1;
  min-height: 0;
}
```

### 参考资料
https://juejin.cn/post/6931638878512087053
https://www.w3.org/TR/css-flexbox-1/#min-size-auto
