### ISSUE TITLE
微信小程序open-data显示圆形头像

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#512]
view需要包住 open-data, 重点是需要`overflow:hidden`

```html
  <view class="avatar">
    <open-data class="avatar" type="userAvatarUrl"></open-data>
  </view>
```

```css
  .avatar {
    width: 100rpx;
    height: 100rpx;
    border-radius: 50%;
    overflow: hidden;
  }
```
