### ISSUE TITLE
小程序下拉窗口, 非下拉刷新

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#528]
```html
<!--index.wxml-->
<view
  class="container"
  bindtouchstart="touchStart"
  bindtouchmove="touchMove"
  bindtouchend="touchEnd"
>
  <view class="top-block" style="top:{{topTop}}px;left: {{showBlock ? '0' : '-1000px'}};">
    <button bindtap="closeBlock">关闭</button>
  </view>
  <view class="usermotto">
    <text class="user-motto">{{motto}}</text>
  </view>
</view>
```

```js
Page({
  data: {
    showBlock: false,
    startTouchY: 0,
    windowHeight: 0,
    topTop: 0,
    motto: 'Hello World',
    isOpen: false
  },
  onLoad() {
    const a = wx.getSystemInfoSync()
    this.setData({
      windowHeight: a.windowHeight,
      topTop: -a.windowHeight
    })
    setTimeout(() => {
      this.setData({
        showBlock: true
      })
    }, 800)
  },
  closeBlock() {
    this.setData({
      isOpen: false,
      topTop: -this.data.windowHeight
    })
  },
  touchStart(e) {
    if (this.data.isOpen) {
      return
    }
    this.setData({
      startTouchY: e.touches[0].pageY
    })
  },
  touchMove(e) {
    if (this.data.isOpen) {
      return
    }
    const movePageY = e.touches[0].pageY
    const diffPageY = movePageY - this.data.startTouchY
    if (diffPageY < 0) {
      return
    }
    if (diffPageY > this.data.windowHeight / 1.5) {
      this.setData({
        topTop: 0,
        isOpen: true
      })
    } else {
      this.setData({
        topTop: -this.data.windowHeight + diffPageY
      })
    }
  },
  touchEnd() {
    if (!this.data.isOpen) {
      this.setData({
        topTop: -this.data.windowHeight
      })
    }
  }
})

```

```css
.container {
  position: relative;
  height: 100vh;
}
.top-block {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  left: -1000px;
  width: 100%;
  height: 100%;
  background: #dfdfdf;
  transition: top .3s ease-in;
}
```
