### ISSUE TITLE
Elementui dialog弹框水平居中

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#594]
### 方法
```css
.el-dialog{
  display: flex;
  flex-direction: column;
  margin:0 !important;
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
  max-height:calc(100% - 30px);
  max-width:calc(100% - 30px);
}
.el-dialog .el-dialog__body{
  flex:1;
  overflow: auto;
}
```

### 参考资料
https://blog.csdn.net/Shids_/article/details/120728973
