### ISSUE TITLE
window.print()打印时去除默认的页头页尾

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#598]
```css
<style media="print">
@page {
  size: auto; /* auto is the initial value */
  margin: 0mm; /* this affects the margin in the printer settings */
}
</style>
```
