### ISSUE TITLE
contenteditable添加placeholder

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#679]
```html
<div class="content-input" contentable data-placeholder="testtest">
```
```css
  .content-input:not(:focus):empty::before {
    content: attr(data-placeholder);
    color: #d5d8de;
  }
```
