### ISSUE TITLE
videoJS禁止单击视频暂停

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#68]
```css
.vjs-tech {
  pointer-events: none;
}
```

https://github.com/videojs/video.js/issues/2444
