### ISSUE TITLE
css绘制虚线

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#757]
```css
.dash-line {
  width: 2px;
  height: 100%;
  background: linear-gradient(to top, transparent 0%, transparent 50%, #ccc 50%, #ccc 100%);
  background-size: 10px 1px;
  background-repeat: repeat-y;
}
```
