### ISSUE TITLE
element button 防止一致处于选中的样式

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#799]
```css
.el-button.el-button--primary:not(.is-disabled):focus,
.el-button.el-button--primary:not(.is-disabled):hover {
  background: var(--el-color-primary)!important;
}
.el-button.el-button--primary.is-link:not(.is-disabled):focus,
.el-button.el-button--primary.is-link:not(.is-disabled):hover {
  color:var(--el-color-primary)!important;
}

.el-button.el-button--warning:not(.is-disabled):focus,
.el-button.el-button--warning:not(.is-disabled):hover {
  background: var(--el-color-warning)!important;
}
.el-button.el-button--warning.is-link:not(.is-disabled):focus,
.el-button.el-button--warning.is-link:not(.is-disabled):hover {
  color:var(--el-color-warning)!important;
}

.el-button.el-button--success:not(.is-disabled):focus,
.el-button.el-button--success:not(.is-disabled):hover {
  background: var(--el-color-success)!important;
}
.el-button.el-button--success.is-link:not(.is-disabled):focus,
.el-button.el-button--success.is-link:not(.is-disabled):hover{
  color:var(--el-color-success)!important;
}

.el-button.el-button--info:not(.is-disabled):focus,
.el-button.el-button--info:not(.is-disabled):hover {
  background: var(--el-color-info)!important;
}
.el-button.el-button--info.is-link:not(.is-disabled):focus,
.el-button.el-button--info.is-link:not(.is-disabled):hover {
  color:var(--el-color-info)!important;
}

.el-button.el-button--danger:not(.is-disabled):focus,
.el-button.el-button--danger:not(.is-disabled):hover {
  background: var(--el-color-danger)!important;
}
.el-button.el-button--danger.is-link:not(.is-disabled):focus,
.el-button.el-button--danger.is-link:not(.is-disabled):hover{
  color:var(--el-color-danger)!important;
}

```
