### ISSUE TITLE
swiper闪烁问题

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#848]
`https://github.com/nolimits4web/swiper/issues/3527`

设置`cssMode`为`true`

**Comment by klren0312** [comment]
```css
.swiper-wrapper {
  transform: translate3d(0,0,0);
  overflow: hidden;
}

.swiper-slide {
  transform: translate3d(0,0,0);
}
```
