### ISSUE TITLE
顶部提示弹框

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#87]
### 示例
![1](https://user-images.githubusercontent.com/10903843/61941248-ab601980-afc9-11e9-929c-4e0a0949e046.gif)

### 原生版
```javascript
function showToast(text, type) {
  var random = Math.floor(Math.random()*100000)
  var body = document.querySelector('body')
  var toast = document.createElement('div')
  toast.className = 'toast ' + type + ' t' + random
  toast.innerHTML = text
  body.appendChild(toast)
  var currentToast = document.querySelector('.toast.' + type + '.t' + random)
  currentToast.style.opacity = 1
  setTimeout(function () {
    currentToast.style.opacity = 0
    setTimeout(function () {
      body.removeChild(currentToast)
    }, 800);
  }, 4000)
}
```
### JQ版
```javascript
function showToast(text, type) {
  var random = Math.floor(Math.random()*100000)
  $('body').append($('<div class="toast ' + type + ' t' + random + '"></div>').text(text))
  $('.toast.' + type + '.t' + random).animate({
    opacity: 1
  })
  setTimeout(function () {
    $('.toast.' + type + '.t' + random).animate({
      opacity: 0
    })
    setTimeout(function () {
      $('.toast.' + type + '.t' + random).remove()
    }, 800);
  }, 4000)
}
```
### CSS
```css
.toast {
  position: fixed;
  left: 50%;
  top: 30px;
  // transform: translateX(-50%);
  // transition: opacity .3s,transform .4s,top .4s;
  z-index: 1;
  min-width: 60px;
  align-items: center;
  pointer-events: all;
  padding: 8px 16px;
  border-radius: 4px;
  box-shadow: 0 1px 6px rgba(0,0,0,.2);
  background: #fff;
  color: #009688;
  opacity: 0;
  -webkit-animation: bounceInDown .5s;
  animation: bounceInDown .5s;
  &.success {
    color: #009688;
  }
  &.error {
    color: #f56c6c;
  }
}

@-webkit-keyframes bounceInDown {
  from,
  60%,
  75%,
  90%,
  to {
    -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
    animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
  }

  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -3000px, 0);
    transform: translate3d(0, -3000px, 0);
  }

  60% {
    opacity: 1;
    -webkit-transform: translate3d(0, 25px, 0);
    transform: translate3d(0, 25px, 0);
  }

  75% {
    -webkit-transform: translate3d(0, -10px, 0);
    transform: translate3d(0, -10px, 0);
  }

  90% {
    -webkit-transform: translate3d(0, 5px, 0);
    transform: translate3d(0, 5px, 0);
  }

  to {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}

@keyframes bounceInDown {
  from,
  60%,
  75%,
  90%,
  to {
    -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
    animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
  }

  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -3000px, 0);
    transform: translate3d(0, -3000px, 0);
  }

  60% {
    opacity: 1;
    -webkit-transform: translate3d(0, 25px, 0);
    transform: translate3d(0, 25px, 0);
  }

  75% {
    -webkit-transform: translate3d(0, -10px, 0);
    transform: translate3d(0, -10px, 0);
  }

  90% {
    -webkit-transform: translate3d(0, 5px, 0);
    transform: translate3d(0, 5px, 0);
  }

  to {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}
```
