### ISSUE TITLE
absolute, fixed 元素水平居中

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#89]
```html
<div class="test"></div>
```
**1.**
```css
.test {
  display: absolute;
  left: 0;
  right: 0;
  margin: 0 auto;
}
```

**2.**
```css
.test {
  display: absolute;
  left: 50%;
  transform: translateX(-50%);
}
```
