### ISSUE TITLE
HTML多行文本省略

### ISSUE THREAD

**Issue by klren0312** [klren0312/daliy_knowledge#91]
### 示例
![image](https://user-images.githubusercontent.com/10903843/62034653-fc1d7f80-b220-11e9-8092-77633a09995d.png)

### 原理
将文本和省略号放在一个`div(class="text-block")`下, 通过比较外层div高度与设定的高度(wantHeight), 来对文本进行删减.
### 代码
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <style>
    .text-block {
      width: 200px;
    }
    .text-content {
      word-break: break-all;
    }
    .text-ellipsis {
      display: inline-block;
    }
  </style>
</head>
<body>
  <div class="text-block">
    <span class="text-content">传播数据可视化，热点分析立体化。分布式采集框架大幅提高采集效率，最大支持 200集群节点，单日数据采集量可达亿级别。</span>
    <span>...</span>
  </div>

  <script>
    var textDom = document.querySelector('.text-content')
    var block = document.querySelector('.text-block')
    var wantHeight = 100
    n = 1000
    while (block.offsetHeight > wantHeight  && n > 0) {
      var text = textDom.innerText
      if (block.offsetHeight > wantHeight  * 3) {
        textDom.innerText = text.substring(0, Math.floor(text.length / 2))
      } else {
        textDom.innerText = text.substring(0, text.length - 1)
      }
      n--
    }
  </script>
</body>
</html>
```

**Comment by klren0312** [comment]
### 使用CSS
```css
.text-block {
  width: 200px;
  display: -webkit-box;
  -webkit-line-clamp: 4;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
```html
<div class="text-block">
  传播数据可视化，热点分析立体化。分布式采集框架大幅提高采集效率，最大支持 200集群节点，单日数据采集量可达亿级别。
</div>
```
